network:
    ethernets:
        enp1s0:
            optional: true
            dhcp4: true
        enp2s0:
            optional: true
            dhcp4: false
        enp3s0:
            optional: true
            dhcp4: false
        enp4s0:
            optional: true
            dhcp4: false
    bridges:
        br0:
            interfaces:
                - enp2s0
                - enp3s0
            dhcp4: false
            optional: true
    version: 2

